//
// Created by ajl on 2021/11/12.
//

#ifndef HUAGERTP_APP_EXTERN_H
#define HUAGERTP_APP_EXTERN_H

enum PLTYPE {
    ENU_PLTYPENONE = 0, ENU_PLTYPETEXT,ENU_PLTYPEAUDIO, ENU_PLTYPEVIDEO
};
#endif //HUAGERTP_APP_EXTERN_H
